#token:
#  expiration_time: 86400000
#  secret: user_token_user#

gateway:
  ip: 192.168.219.161

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://redsky21.duckdns.org:3306/msa_order_db
    username: boot
    password: '{cipher}AQANSdtmMkqaRA+khPPPhOB0ePHiaQziaJ9dGimJzfe7aU4+ADmKTFK5rZdhmyh/Y4R/jJsEFgpuUk8MvUJsbGk/NbGRmyIT7W9eiagumHu2lF42w3E4SWgOPVXKbsqpzlXF0OB8V0C+rGtWuKid9mEhcGbJV4uuDT4EVZWNauMpVBYNp/Zj50FxkPsuPGdqDJAcyVlUN9hwVXuaJrdrt1piV7MUKqXJ2qudhcFjEGJzBm96fIj57ckUIpl63Txl1s7yv3pMGJfflc+whOmXRoMFWX9nnihcCeiDu+g16GJrMvfbMBMMYPz/m2p2vLaPWz49mYtAxf2i2MaeSv7BEZH/s0RW7BOZl9BiI5rkVTu90HqHDtaTD56hSBFJHIOWsKw='
