#token:
#  expiration_time: 86400000
#  secret: user_token_user#

gateway:
  ip: 192.168.219.161

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://redsky21.duckdns.org:3306/msa_order_db
    username: boot
    password: "{cipher}2555ce5346c765f89e7379e48d4d1c49b1d3cff182e66bb8c7f0c9773162ab18"
